version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: shortly
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    environment:
      - RS_HOSTS=host.docker.internal:6379
    restart: always