version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shortly
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data